global:
  scrape_interval: 5s
  external_labels:
    monitor: 'prakash-monitor'
scrape_configs:
  #- job_name: 'api-marketplace'
  #  static_configs:
  #    - targets: ['api-marketplace:8081']
  #- job_name: 'nginx'
  #  static_configs:
  #    - targets: ['10.50.4.75:9113']
  #    - targets: ['192.168.31.24:9113']
  #- job_name: 'nginxRequests'
  #  static_configs:
  #    - targets: ['192.168.31.24:3093']
  #    - targets: ['10.50.4.75:3093']
  #- job_name: 'postgres'
  #  static_configs:
  #    - targets: ['192.168.31.24:9187']
  #    - targets: ['10.12.170.75:9187']
  #  #  - targets: ['10.12.170.220:9188']
  #- job_name: 'prometheus'
  #  static_configs:
  #    - targets: ['192.168.31.24:9090'] ## IP Address of the localhost
  #    - targets: ['10.12.170.75:9090']
#  - job_name: 'krakend'
#    static_configs:
#      - targets: ['10.12.170.220:9091']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['172.17.0.4:9100']
  #    - targets: ['10.12.170.220:9100']
  #    - targets: ['10.12.170.75:9100']
  #    - targets: ['10.12.170.193:9100']
  #    - targets: ['10.50.4.75:9100']
  #    - targets: ['192.168.31.24:9100']
  #    - targets: ['192.168.31.25:9100']
  #    - targets: ['192.168.31.45:9100']
#      - targets: ['10.30.0.122:9100']
  - job_name: 'cAdvisor'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['172.17.0.5:8084']
  #    - targets: ['10.12.170.220:8085']
  #    - targets: ['10.12.170.75:8085']
  #    - targets: ['10.50.4.75:8085']
  #    - targets: ['10.12.170.193:8085']
  #    - targets: ['192.168.31.24:8085']
  #    - targets: ['192.168.31.25:8085']
  #    - targets: ['192.168.31.45:8085']
#     - targets: ['10.30.0.122:8085']

        #labels:
        #  group: 'cadvisor'
#  - job_name: 'nginxRequests'
#    metrics_path: '/metrics'
#    static_configs:
#      - targets: ['192.168.31.24:3093']
